export function lucky() {
  const random_tasks = [
    "Make your bed 🛏️",
    "Clean your workspace 🧹",
    "Wash the dishes 🍽️",
    "Vacuum the floor 🧹",
    "Dust off shelves 🧽",
    "Fold the laundry 🧺",
    "Take out the trash 🚮",
    "Organize closet 👗",
    "Water plants indoors 🌱",
    "Change bed sheets 🛏️",
    "Sort your email inbox 📧",
    "Write down three daily goals 📝",
    "Plan tomorrow’s schedule 🗓️",
    "Unsubscribe from spam emails 📧",
    "Update your calendar 📅",
    "Set a reminder for an important task ⏰",
    "Plan a grocery list 🛒",
    "Create a simple Excel chart 📊",
    "Write an email to a colleague or classmate 📧",
    "Prepare a simple meal plan 🥗",
    "Do a quick workout for 10 minutes 💪",
    "Set a daily step goal 🚶‍♂️",
    "Write a to-do list for today 📋",
    "Review your monthly goals 🏆",
    "Schedule a doctor’s appointment 🗓️",
    "Research a skill related to your job or hobby 🔍",
    "Update your resume 📝",
    "Practice typing skills ⌨️",
    "Declutter one shelf or drawer 🗄️",
    "Clean your computer desktop 🖥️",
    "Backup your important files 💾",
    "Organize your digital photos 📸",
    "Create a morning routine 🗓️",
    "Drink 8 cups of water 💧",
    "Meditate for 5 minutes 🧘",
    "Stretch for 5 minutes 🤸",
    "Do 10 push-ups 💪",
    "Take 10 deep breaths 🌬️",
    "Go for a short walk 🚶‍♀️",
    "Eat a fruit or vegetable 🍎",
    "Do 15 minutes of yoga 🧘",
    "Listen to calming music 🎶",
    "Take a power nap 😴",
    "Sit in silence for 2 minutes 🤫",
    "Do 10 squats 🏋️‍♀️",
    "Stand up and move around 🕺",
    "Brush your teeth 🪥",
    "Take a relaxing shower 🚿",
    "Smile for 30 seconds 😊",
    "Make a creative collage 📸",
    "Draw or sketch something 🎨",
    "Paint a picture 🖌️",
    "Compose a new melody 🎶",
    "Write a short story 📝",
    "Write a poem ✏️",
    "Make a playlist of favorite songs 🎧",
    "Build a simple craft project 🔨",
    "Make a greeting card 💌",
    "Design a simple flyer 🎨",
    "Practice calligraphy ✍️",
    "Try origami paper folding 🦋",
    "Take creative photographs 📷",
    "Learn to play a chord on guitar 🎸",
    "Write down a few business ideas 💡",
    "Record a short song or rap 🎤",
    "Rearrange your furniture 🛋️",
    "Make a jewelry or bead craft 📿",
    "Collect leaves and paint them 🍂",
    "Write a script for a short play 🎭",
    "Write 3 things you’re grateful for 🙏",
    "Create a photo story collage 📸",
    "Design a T-shirt pattern 👕",
    "Watch a funny video online 😂",
    "Play a board game 🎲",
    "Play a video game 🎮",
    "Dance to your favorite song 💃",
    "Sing karaoke 🎤",
    "Try a new ice cream flavor 🍦",
    "Fly a kite on a windy day 🪁",
    "Try juggling 🤹",
    "Visit a park and take photos 🌳",
    "Host a mini quiz night 🏆",
    "Try a new workout video 🏋️‍♂️",
    "Solve a Sudoku puzzle 🔢",
    "Build a fort with pillows 🏰",
    "Make popcorn and watch a movie 🍿",
    "Try a simple magic trick 🪄",
    "Learn a new dance move 🤸",
    "Do a handstand or cartwheel 🤸",
    "Plan a picnic outing 🧺",
    "Create a scavenger hunt 🧭",
    "Watch a nature documentary 🦁",
    "Play hopscotch or skip rope 🏃",
    "Write a joke and share it 😄",
    "Bake a funny face cake 🎂",
    "Listen to a comedy podcast 🎧",
    "Take a silly selfie 🤳",
    "Read an interesting article 📰",
    "Watch a documentary 🎥",
    "Learn a word in another language 🌐",
    "Solve a crossword puzzle 🧩",
    "Research a topic you’re curious about 🔍",
    "Listen to an educational podcast 🎙️",
    "Study a chapter of a book 📚",
    "Learn about the stars 🌌",
    "Take an online quiz 📝",
    "Practice mental math 🧠",
    "Study for an upcoming test 📖",
    "Read a biography 📖",
    "Watch a TED talk 🎤",
    "Learn the basics of coding 🖥️",
    "Explore a new hobby tutorial 🎬",
    "Memorize 5 world capital cities 🌎",
    "Research a historical event 🏺",
    "Try a coding challenge 💻",
    "Build a simple webpage 🌐",
    "Learn a computer shortcut ⌨️",
    "Update your software 💾",
    "Change your desktop wallpaper 🖼️",
    "Clear your web browser cache 🗑️",
    "Set an alarm on your smartphone ⏰",
    "Join a developer forum 👥",
    "Learn about cybersecurity 🔒",
    "Create a mobile app idea 📱",
    "Drink a glass of water 💧",
    "Meditate or do yoga 🧘",
    "Stretch your body 🤸",
    "Do 5-minute wall sit 🧍",
    "Practice deep breathing 🌬️",
    "Eat a healthy snack 🥑",
    "Get fresh air outside 🌳",
    "Keep a gratitude journal 📓",
    "Listen to relaxing music 🎶",
    "Smile at yourself in the mirror 😊",
    "Give yourself a 2-min facial massage 💆",
    "Plan a quick healthy meal 🍲",
    "Hold a plank for 1 minute 💪",
    "Take a 5-minute mindfulness break 🧘",
    "Call a family member 📞",
    "Text a friend or relative 💬",
    "Write a thank-you note ✍️",
    "Compliment someone you meet 😊",
    "Volunteer locally 🤝",
    "Help a neighbor with groceries 🛒",
    "Plan a lunch with a friend 🥗",
    "Teach someone a new skill 📖",
    "Share a positive meme 😆",
    "Bake cookies for a friend 🍪",
    "Donate unused items 🎁",
    "Organize a virtual hangout 🎉",
    "Plant a tree 🌳",
    "Give someone a hug 🤗",
    "Write a kind comment online 🖥️",
    "Invite a friend for a walk 🚶‍♂️",
    "Organize the closet 👗",
    "Sort recycling ♻️",
    "Sweep the floor 🧹",
    "Take out the trash 🚮",
    "Sort laundry 🧺",
    "Clean the windows 🪟",
    "Check the mailbox 📬",
    "Unclutter your desk 🗂️",
    "Organize the pantry 🍲",
    "Vacuum the porch 🌿",
    "Check your bank balance 💰",
    "Plan a budget 📊",
    "Save loose change 💵",
    "Compare prices online 🛒",
    "Learn basic investing 📈",
    "Set a savings goal 💰",
    "Track today's expenses 🧮",
    "List 3 ways to save money 💡",
    "Read a finance article 📰",
    "Update LinkedIn profile 👔",
    "Research a career field 🔍",
    "Draft a cover letter ✍️",
    "Practice interview questions 🎤",
    "Clean your work desk 🗂️",
    "Learn a new Excel skill 📊",
    "Plan a career goal 🏅",
    "Read a work-related blog 🖥️",
    "Send a thank-you email 💌",
    "Write your to-do list for tomorrow 📋",
    "Rearrange your room 🛋️",
    "Water an outdoor plant 🌳",
    "Write a short poem 📜",
    "Describe the sky to a friend ☁️",
    "Take a different route home 🛣️",
    "List your favorite books 📚",
    "Create a vision board 📌",
    "Say thank you to someone 🎁",
    "Polish your glasses 👓",
    "Practice a foreign accent 🎭",
    "Watch the sunrise or sunset 🌅",
    "Walk a new neighborhood 🏘️",
    "Donate old books to a library 📚",
    "Learn 5 sign language signs 🤟",
    "Make a quick fruit salad 🍎",
    "Write your daily affirmation 😊",
    "Try a speed clean of one room 🧹",
    "Research eco-friendly tips 🍃",
    "Update old passwords 🔑",
    "Read the first chapter of a book 📖",
    "Memorize a poem or quote 📜",
    "Organize your phone apps 📱",
    "Cook a recipe you've never tried 🍳",
    "Plan your next weekend activity 📅",
    "Practice solving a Rubik's cube 🧩",
    "Write down a short-term goal 📋",
    "Donate blood or register online 🩸",
    "Learn to say 'Hello' in 5 languages 👋",
    "Try a new hairstyle or outfit 👗",
    "Create a quick origami figure 🦢",
    "Research how to learn a new skill 📖",
    "Watch a science experiment video 🔬",
    "Make a list of simple joys 😊",
    "Tidy up your living area 🛋️",
    "Organize a bookshelf by color 📚",
    "Practice patience with deep breaths 🧘",
    "Do a random act of kindness 💌",
    "Review your to-do list 📋",
    "Set a sleep alarm 30 min earlier ⏰",
    "Play a strategy mobile game 📱",
    "Write down a fun memory 📝",
    "Organize desktop icons 🖥️",
    "Find 5 new facts about an animal 🐘",
    "Sketch a DIY home décor plan 🏡",
    "Plan next month’s goals 📅",
    "Celebrate a small win 🎉",
    "Create a habit tracker 📊",
    "Research starting a small business 💼",
    "Find free learning resources online 📚",
    "Sketch your favorite animal 🦁",
    "Practice typing with left hand ⌨️",
    "Plan a tech-free evening 📵",
    "Donate unused clothes 🎽",
    "List 5 countries in Asia 🌏",
    "Count backward from 100 by sevens 🔢",
    "Learn one word in Morse code 🔤",
    "Try a fitness yoga balance pose 🧘",
    "Draw your family as cartoons 🖼️",
    "Collect 3 different types of leaves 🍂",
    "Invent a simple story plot 📖",
    "Make a quick video diary 🎥",
    "Clean out your email inbox 📧",
    "Write 5 things you love about today ❤️",
    "Research a free online course 🖥️",
    "Practice mindfulness with breathing 🌬️",
    "Look up at the sky for one minute ☁️",
    "Share a helpful tip on social media 📲",
    "Organize 5 smartphone apps by use 📱",
    "Learn a new emoji meaning 🤔",
    "Take photos of 3 shades of green 🌳",
    "Check an interesting news headline 📰",
    "Sort mailbox: mark junk vs important 📬",
    "Set a daily water intake goal 💧",
    "Write a blog post outline 📝",
    "Send a positive text message 🌟",
    "Research how to plant a garden 🌱",
    "Learn a phrase in sign language 🤟",
    "Make a small budget plan 💵",
    "Watch a dance tutorial 💃",
    "Draw with your eyes closed ✏️",
    "Organize your email folders 📧",
    "Learn to play a simple song 🎶",
    "Plan an upcoming family outing 🏖️",
    "Listen to weather forecast for tomorrow 🌦️",
    "Cook a vegetarian meal 🥕",
    "Try a breathing relaxation technique 🧘‍♀️",
    "Sort your recycle bin ♻️",
    "Plan a charity project idea 🎗️",
    "Update a profile picture 📸",
    "Learn basic car maintenance skills 🔧",
    "Make an emergency contact list ☎️",
    "Try talking backwards for fun 🤪",
    "Write a daily gratitude sentence 🙏",
    "Organize a fun playlist 🎵",
    "Draw or color a mandala 🌀",
    "Practice balancing on one foot 🚶‍♂️",
    "Learn to whistle with fingers 🎵",
    "Find a volunteer opportunity 🤝",
    "Complete a fun online quiz 🧠",
    "Write a new to-do task on paper 📃",
    "Play an educational mobile game 🧮",
    "Visualize a goal while closing eyes 💭",
    "Organize cables and chargers 🔌",
    "Write 3 positive affirmations 💡",
    "Design your dream workspace 🖥️",
    "Watch a motivational speech 🎧",
    "Cook a healthy snack 🥗",
    "Brainstorm ideas for a hobby 💡",
    "Read a science fun fact 🔬",
    "Plan a visit to a museum 🏛️",
    "Practice keyboard typing test ⌨️",
    "Take a quick Internet break 📵",
    "Write a short movie review 🎥",
    "Learn a new card game rule ♠️",
    "Draw a map of your neighborhood 🗺️",
    "Plan to spend 30 mins reading 📖",
    "Listen to a language learning app 🎧",
    "Find a classical music piece 🎼",
    "Create a quick coloring page 🖍️",
    "Arrange a book shelf by genre 📚",
    "Check the news in another language 🌎",
    "Think of a new startup idea 💡",
    "Do a quick brain teaser puzzle 🧩",
    "Copy your favorite quote 📜",
    "Try a quick photography experiment 📷",
    "Create a small workout circuit 🏋️",
    "Set a timer to clean something ⏲️",
    "Write a motivation letter ✍️",
  ];
  return random_tasks[Math.floor(Math.random() * random_tasks.length)];
}
